replicaCount: 2

image:
  repository: linux02.local/myapp/flask-demo-2
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "20260701050715-3e5d8e1"
# This is for the secrets for pulling an image from a private repository more information can be found here: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
imagePullSecrets:
  - name: harbor-secret

containerPort: 8080

host: flask-demo-2.local

# canary steps driven by Argo Rollouts; setWeight becomes Istio VS weight
canary:
  steps:
    - setWeight: 50
    - pause: {}
